services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /var/lib/docker/volumes/
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    name: postgres
    driver: bridge